id: ACD521D79
title: Guru Sādhana of Glorious Dharmakīrti
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:15:09.688190
  last_modified_at: 2022-03-01 02:15:09.688216
